# -*- coding: utf-8 -*-
"""Seviye dosyalarina gomulu kitap, gunluk, mektup ve not metinleri.

Bunlar dunyada okunan yazilar: Corlian'in gunlugu, Tarikat yazismalari, arena
kutuphanesi, siirler, listeler. objstrings.rdb'de DEGIL, her .rfc'nin icindeki
gomulu RDB'de duruyorlar (bkz. tr_rfc.py).

TERIMLER (oyunun geri kalaniyla birebir)
  thaumaturge -> tomaturjist      Order of Thaumaturges -> Tomaturjistler Tarikati
  necromancer -> nekromant        necromancy -> nekromantlik
  binding -> bag                  proctor -> vekil
  Guardian -> Muhafiz             Spellgiver -> Buyu Bahseden
  Corruptor -> Yozlastiran        transcendence -> askinlik
  conservers -> koruyucular       sentries -> nobetciler

USLUP: gunlukler ve mektuplar 1. tekil, donemsel ve olculu bir dil; kitap
tanitimlari 2. tekil gozlemci ("...anlayabiliyorsun"), obj_tr.json'daki esya
aciklamalariyla ayni anlatici sesi.

{®Exanima.Unknown.HeShe} gibi yer tutucular AYNEN korunur.
"""

TR = {
    # ---------------- arena kutuphanesi ----------------
    'A nice looking bottle. You notice someone scratched "Rob" on the bottom of it.':
        'Güzel görünüşlü bir şişe. Altına birinin "Rob" kazıdığını fark ediyorsun.',
    'The Healing Power of Flora and Fungi':
        'Bitkilerin ve Mantarların Şifa Gücü',
    'An extensive list of recipes to help cure all manner of common ailments. Ointments, poultices, drinks and soups, the remedies are accompanied by colourful illustrations and even guides as to where one may locate the relevant plants, herbs and mushrooms contained within them. ':
        'Her türlü yaygın rahatsızlığı iyileştirmeye yarayan uzun bir tarif listesi. Merhemler, lapalar, içecekler ve çorbalar; devaların yanında renkli resimler, hatta içlerindeki bitkilerin, otların ve mantarların nerede bulunabileceğine dair kılavuzlar da var. ',
    'A guide to blood and its many uses in the field of medicine. How blood functions in the body and why it is so vital to health. There are also sections of the book that deal with the history of blood work in the medical field, and the mythology and folklore surrounding blood in a more general sense. Apparently there was once a cult that mimicked a certain annoying insect and sustained themselves on a diet of nothing but the blood of other humans, believing mistakenly it would give them eternal life.':
        'Kan ve onun hekimlikteki pek çok kullanımı üzerine bir kılavuz. Kanın bedende nasıl işlediği ve sağlık için neden bu denli hayati olduğu. Kitabın hekimlikte kan çalışmalarının tarihine, ayrıca kanı çevreleyen efsane ve halk inançlarına ayrılmış bölümleri de var. Anlaşılan bir zamanlar, can sıkıcı bir böceği taklit eden ve kendini yalnızca insan kanıyla besleyen bir tarikat varmış; bunun onlara sonsuz yaşam vereceğine yanlışlıkla inanıyorlarmış.',
    'The Book of Stones': 'Taşlar Kitabı',
    'Not, as one may guess, a guide to the treatment of liver and bladder stones. Rather an elaborate and extensive list of minerals, their properties, and how one may use them in medicinal practices. The largest section of the book deals with the processes that must be followed in order to properly extract a specific mineral from certain types of rock.\r\n':
        'Sanılabileceği gibi safra ve mesane taşlarının tedavisine dair bir kılavuz değil. Daha çok, minerallerin ayrıntılı ve uzun bir listesi: özellikleri ve hekimlikte nasıl kullanılabilecekleri. Kitabın en uzun bölümü, belirli kaya türlerinden belirli bir minerali düzgünce çıkarmak için izlenmesi gereken işlemleri anlatıyor.\r\n',
    "The Practitioner's Guide": 'Hekimin El Kitabı',
    "Book I - Diagnosis\r\n\r\nExplains the necessary steps required to properly diagnose a patient's condition or disease. Notable chapters include: Physical testing and examination. Determining a patient's medical history by means of written record. Determining a patient's medical history by interview or questionnaire. Diagnostic procedures. How best to avoid misdiagnosis. How best to give the bad news. How best to avoid contracting illness yourself. Lastly a chapter called: What is that? No I'm not touching it, get away from me! Deals with the most grotesque and repulsive boils, warts, rashes and sexually transmitted diseases.":
        'Kitap I - Tanı\r\n\r\nBir hastanın durumunu ya da hastalığını doğru teşhis etmek için gereken adımları anlatıyor. Dikkat çeken bölümler: Fiziksel muayene ve sınama. Yazılı kayıtlardan hastalık geçmişini çıkarma. Görüşme ya da soru listesiyle hastalık geçmişini çıkarma. Tanı işlemleri. Yanlış teşhisten en iyi nasıl kaçınılır. Kötü haber en iyi nasıl verilir. İnsan kendine hastalık bulaştırmaktan en iyi nasıl korunur. Son olarak şu başlıklı bölüm: O da ne? Hayır, ona dokunmuyorum, çekil yanımdan! En iğrenç ve tiksindirici çıbanları, siğilleri, döküntüleri ve cinsel yolla bulaşan hastalıkları ele alıyor.',
    'The Power of Blood': 'Kanın Gücü',
    'Book II - Anatomy\r\n\r\nA detailed guide to the human anatomy. Every limb, organ, vessel, tissue, bone and muscle broken down and elaborated on to great extent. Full of near perfectly accurate illustrations, strange sounding names and terms, and lists of functions.\r\n':
        'Kitap II - Anatomi\r\n\r\nİnsan anatomisine dair ayrıntılı bir kılavuz. Her uzuv, organ, damar, doku, kemik ve kas tek tek ayrılıp uzun uzun anlatılmış. Neredeyse kusursuz doğrulukta resimler, kulağa tuhaf gelen adlar ve terimler, işlev listeleriyle dolu.\r\n',
    'Book III - Treatment \r\n\r\nA glossary of every known condition or disease. The book does not offer specifics in how to prepare and administer treatments. Rather it lists the name of the illness then references other books where the specifics may be found, mainly within The Books of Healing written by the same author.\r\n':
        "Kitap III - Tedavi \r\n\r\nBilinen her rahatsızlık ve hastalığın sözlüğü. Kitap tedavilerin nasıl hazırlanıp uygulanacağını ayrıntısıyla vermiyor. Bunun yerine hastalığın adını sıralayıp ayrıntıların bulunabileceği başka kitaplara, özellikle aynı yazarın Şifa Kitapları'na gönderme yapıyor.\r\n",
    'The Books of Healing': 'Şifa Kitapları',
    'Book I - Herbs and Plants \r\n\r\nAn extensive examination of the healing properties of herbs and plants. The book is organised into two sections. The first lists individual plants and herbs, what properties they have and the \r\nillnesses they treat, even going as far as how best to cultivate them. The second is dedicated to the preparation of medicines, often involving highly complex and laborious methods.':
        'Kitap I - Otlar ve Bitkiler \r\n\r\nOtların ve bitkilerin şifa özellikleri üzerine geniş bir inceleme. Kitap iki bölüme ayrılmış. İlki tek tek bitki ve otları, hangi özellikleri taşıdıklarını ve hangi \r\nhastalıkları iyileştirdiklerini sıralıyor; hatta en iyi nasıl yetiştirileceklerine kadar gidiyor. İkincisi, çoğu zaman karmaşık ve zahmetli yöntemler gerektiren ilaç hazırlamaya ayrılmış.',
    'Book II - Animals \r\n\r\nPrimarily details the usage of animals in the preparation of various medicines. Everything from breast milk, to gall, to ground bone marrow and even brain tissue, are suggested as vital ingredients in treatments for a range of diseases and lesser ailments. ':
        'Kitap II - Hayvanlar \r\n\r\nBaşlıca, çeşitli ilaçların hazırlanmasında hayvanların kullanımını anlatıyor. Anne sütünden safraya, öğütülmüş ilikten beyin dokusuna kadar her şey, bir dizi hastalık ve hafif rahatsızlığın tedavisinde vazgeçilmez bileşen olarak öneriliyor. ',
    'Book III - Oils, Potions and Brews \r\n\r\nA kind of extension to the first two books in the series. This book covers old ground, as well as going into deeper detail on the preparation of various healing liquids. It also introduces new, more advanced, and sometimes esoteric methods. Many ingredients for the brews and oils it lists can not be found on the surface and are totally unfamiliar. \r\n':
        'Kitap III - Yağlar, İksirler ve Karışımlar \r\n\r\nDizinin ilk iki kitabının bir tür devamı. Bu kitap eski konuları yeniden ele alıyor, ayrıca çeşitli şifalı sıvıların hazırlanışına daha derinlemesine giriyor. Yeni, daha ileri ve zaman zaman gizemli yöntemler de sunuyor. Sıraladığı karışım ve yağların pek çok bileşeni yeryüzünde bulunmuyor ve tümüyle yabancı. \r\n',
    'Book IV = Amulets \r\n\r\nA list of unknown legendary objects with healing proprieties.\r\nA wild tangent is taken in the series here as it seems to primarily deal with thaumaturgic principles. Very little of it can be understood, other than the names and properties of various rare or totally unknown substances. The processes and methods it details are too far fetched to be accurate, perhaps the author wrote it in his old age, or perhaps it was meant as a work of fiction.\r\n':
        'Kitap IV = Muskalar \r\n\r\nŞifa özelliği taşıyan, bilinmeyen efsanevi nesnelerin bir listesi.\r\nDizi burada iyice konudan sapıyor; ağırlıklı olarak tömaturji ilkeleriyle uğraşıyor gibi. Çeşitli ender ya da tümüyle bilinmeyen maddelerin adları ve özellikleri dışında pek az şey anlaşılabiliyor. Anlattığı işlemler ve yöntemler doğru olamayacak kadar akıl dışı; belki yazar bunu yaşlılığında kaleme aldı, belki de baştan bir kurgu olarak tasarlandı.\r\n',

    # ---------------- exanima01 ----------------
    'A tattered padded cloth gambeson.': 'Yıpranmış, dolgulu bir kumaş gambison.',
    'A pair of hardened leather vambraces in poor condition.':
        'Kötü durumda, sertleştirilmiş deriden bir çift kolluk.',
    'A badly worn leather cap.': 'Fena hâlde yıpranmış bir deri başlık.',
    "A detailed log of various materials being delivered and dispatched. The script and some of the spelling seem very unusual. What you assume must be dates have a format that you can't make sense of.":
        'Çeşitli malzemelerin teslim ve sevkine dair ayrıntılı bir kayıt defteri. Yazı biçimi ve kimi imlalar çok alışılmadık görünüyor. Tarih olduğunu varsaydığın şeyler, anlam veremediğin bir düzende yazılmış.',
    "Consignment has arrived, I must find a suitable place and begin work. Finally I can resume living with a vague semblance of decency. I cannot stand this filth any longer, I've been living like an animal.":
        'Sevkiyat geldi; uygun bir yer bulup işe başlamalıyım. Nihayet insana yakışır bir düzene benzer bir şeyle yaşamaya dönebilirim. Bu pisliğe daha fazla dayanamıyorum, bir hayvan gibi yaşıyordum.',
    'They lose the will to live without their bodies. They seem completely bound to their mortal remains. Is it just because of their lesser minds? I have attempted to sustain one with nothing left but th...\r\n\r\nGods below, what am I doing? It is horrifying. Sometimes it is as if I suddenly wake to realise that I am fuelled by rage, as if I hold these poor souls responsible for what has befallen me.':
        'Bedenleri olmadan yaşama istencini yitiriyorlar. Ölümlü kalıntılarına tümüyle bağlı görünüyorlar. Bu yalnızca zihinlerinin küçüklüğünden mi? Elinde şundan başka bir şey kalmamış birini ayakta tutmayı denedim...\r\n\r\nAşağıdaki tanrılar aşkına, ben ne yapıyorum? Korkunç. Bazen ansızın uyanıp öfkeyle beslendiğimi fark ediyorum; sanki başıma gelenlerden bu zavallı ruhları sorumlu tutuyorum.',
    "I think my illness has worsened since coming here, I often feel confused, as if battling conflicting thoughts. My temper keeps getting the better of me, an aggressive trait I never knew I posessed. Perhaps it is simply a response to all that has happened. Even so it scares me, I don't recognise myself. I must make a greater effort to retain my composure.":
        'Sanırım buraya geldiğimden beri hastalığım ağırlaştı; sık sık kafam karışıyor, sanki birbiriyle çatışan düşüncelerle boğuşuyorum. Öfkem sürekli bana galip geliyor; bende olduğunu hiç bilmediğim saldırgan bir yan. Belki de yalnızca olan biten her şeye bir tepkidir. Yine de beni korkutuyor, kendimi tanıyamıyorum. Soğukkanlılığımı korumak için daha çok çaba göstermeliyim.',
    'So far results are disappointing. I suppose I should have expected as much after the initial dramatic progress. I am seeing some improvement but I feel as though I need a change in direction to really go further. If only poor Papin was still with me, exchanging thoughts with him would benefit me greatly.':
        'Şimdiye dek sonuçlar hayal kırıklığı. Baştaki çarpıcı ilerlemeden sonra bunu beklemeliydim herhâlde. Bir miktar iyileşme görüyorum, ama gerçekten ileri gitmek için yön değiştirmem gerektiğini hissediyorum. Zavallı Papin yanımda olsaydı; onunla düşünce alışverişi bana çok iyi gelirdi.',
    'I feel a growing resentment for Thaven. On the one hand I wish to please him, to impress him, but such thoughts then lead me to anger. I once believed there was friendship between us, now I think perhaps it was based on naught but common interests. His disregard for all things other than his single minded purpose has hurt us, it has put us all in difficulty and danger. I was always feared, but I was also respected. To be driven from my own home by peasants!':
        "Thaven'a karşı büyüyen bir kırgınlık duyuyorum. Bir yandan onu hoşnut etmek, etkilemek istiyorum; ama böyle düşünceler sonra beni öfkeye sürüklüyor. Bir zamanlar aramızda dostluk olduğuna inanırdım; şimdi bunun ortak çıkardan başka bir şeye dayanmadığını düşünüyorum. Tek bir amaç dışında hiçbir şeye aldırmaması bize zarar verdi, hepimizi zorluğa ve tehlikeye soktu. Benden hep korkulurdu, ama bana saygı da duyulurdu. Köylüler tarafından kendi evimden kovulmak!",
    "Hamon has obviously cast aside our agreement. He's sending far too many down here and I've lost all contact with him. What is he trying to do? One of these wretches confessed that he was told to seek treasure. Someone will notice all these missing people. And what if one finds me while I sleep? I no longer feel safe here, I have locked the doors but I should venture further and look for something more secure.":
        'Hamon anlaşmamızı açıkça bir kenara atmış. Buraya çok fazla insan yolluyor ve onunla tüm bağlantımı yitirdim. Ne yapmaya çalışıyor? Bu zavallılardan biri kendisine hazine aramasının söylendiğini itiraf etti. Kaybolan bunca insanı biri fark edecek. Ya biri ben uyurken beni bulursa? Burada artık güvende hissetmiyorum; kapıları kilitledim, ama daha ileri gidip daha sağlam bir yer aramalıyım.',
    "A log of work orders, it seems as though many people were involved in completing them. Most of the names seem strange and many items are described with words you've never seen before.":
        'İş emirlerinin kaydı; bunları tamamlamada pek çok kişinin görev aldığı anlaşılıyor. Adların çoğu tuhaf görünüyor ve pek çok kalem, daha önce hiç görmediğin sözcüklerle tanımlanmış.',
    'A long list of people undergoing treatment of often grevious wounds. Many of the injuries appear to be bites and lacerations, presumably resulting from the attacks of some sort of animal.':
        'Çoğu ağır yara nedeniyle tedavi gören insanların uzun bir listesi. Yaralanmaların birçoğu ısırık ve derin kesik gibi görünüyor; sanırım bir tür hayvanın saldırılarından.',
    "Sal,\r\n\r\nI will, though hurry back, he went for Fabon at inspection causing him to cry out. No harm was done but to his pride, his high pitch drew much laughter. He's declared him unfit for duty, and by the way he talks, we fear he may have more permanent plans. \r\n\r\nTaren":
        "Sal,\r\n\r\nBakarım, ama sen çabuk dön; teftişte Fabon'un üstüne yürüdü, adamcağız bir çığlık attı. Gururundan başka zarar gören olmadı, ama o tiz ses epey kahkaha topladı. Onu görev için elverişsiz ilan etti ve konuşmasına bakılırsa, korkarız daha kalıcı tasarıları var. \r\n\r\nTaren",
    "A catalogue exhaustively describing many common and unremarkable plants in great detail. It's hard to imagine why anyone would undertake such a pointless endeavour.":
        'Pek çok sıradan ve dikkate değmez bitkiyi en ince ayrıntısına dek anlatan bir katalog. Birinin böylesine anlamsız bir işe neden giriştiğini hayal etmek güç.',
    'A list of people assigned guard duty here. The same names are repeated, signed and stamped over and over again. Occasionally a name disappears suddenly and is replaced by another, no reason for this is noted.':
        'Burada nöbete verilen kişilerin listesi. Aynı adlar tekrar tekrar yazılmış, imzalanmış ve mühürlenmiş. Ara sıra bir ad birdenbire kayboluyor ve yerini bir başkası alıyor; buna dair bir gerekçe düşülmemiş.',
    'Letter': 'Mektup',
    "Dearest Mathis,\r\n\r\nElara has disappeared. Many have gone missing of late but bandits in the area are not uncommon. Elara however does not travel, why would they have taken her? I dread to think what they might do to her. I thought of a ransom and so, I am ashamed to admit, I thought of you. But there have been no requests for ransom, just more and more missing. I assume news of these events has not reached Ardent, it has been long since we've seen a proctor. What am I to do dear cousin? Will you at least advise me?\r\n\r\nTessa":
        "Sevgili Mathis,\r\n\r\nElara kayboldu. Son zamanlarda pek çok kişi kayboluyor, ama bu yörede haydut eksik olmaz. Ne var ki Elara yolculuk etmez; onu neden alsınlar? Ona ne yapabileceklerini düşünmek bile içimi ürpertiyor. Fidye geldi aklıma ve utanarak itiraf ediyorum, o yüzden sen geldin. Ama hiç fidye istenmedi, yalnızca kayıplar arttı da arttı. Sanırım bu olayların haberi Ardent'e ulaşmadı; vekil yüzü göreli çok oldu. Ne yapayım sevgili kuzenim? Bari bana akıl verir misin?\r\n\r\nTessa",
    'Book': 'Kitap',
    "In response to our surprising failure we've installed Naiss's ingenious mechanism as a final precaution against intrusion. It can only be operated by those with knowledge of its workings. Simply press all the outer buttons but never two near eachother in sequence before operating it. This will surely keep them out no matter how smart they are.":
        "Şaşırtıcı başarısızlığımıza karşılık, izinsiz girişe son bir önlem olarak Naiss'in dâhice düzeneğini yerleştirdik. Yalnızca işleyişini bilenler çalıştırabilir. Çalıştırmadan önce tüm dış düğmelere basmak yeterli, ama asla art arda yan yana iki tanesine basmayın. Ne kadar zeki olurlarsa olsunlar, bu onları kesinlikle dışarıda tutar.",
    "Darrin, please inform Naiss that he's an idiot. Only a handful of the soldiers are able to reliably operate the mechanism without incident. They don't even understand what they're doing wrong, clearly it is not as simple as he'd have us believe. We've had several incidents already and I'm now having to teach precautions to avoid being burned.":
        "Darrin, lütfen Naiss'e bir budala olduğunu ilet. Askerlerden yalnızca bir avucu düzeneği kazasız belasız çalıştırabiliyor. Neyi yanlış yaptıklarını bile anlamıyorlar; belli ki bize inandırmak istediği kadar basit değil. Şimdiden birkaç kaza yaşadık ve artık yanmamak için alınacak önlemleri öğretmek zorunda kalıyorum.",
    "Taren,\r\n\r\n Leave my key in Han's care. If you're called before I return, I pity any man who try take it.\r\n\r\nSal":
        "Taren,\r\n\r\n Anahtarımı Han'a emanet et. Ben dönmeden çağrılırsan, onu almaya kalkacak adamın hâline acırım.\r\n\r\nSal",
    'The Canine Conductor': 'Köpek Ustası',
    '[algn=2][scrp=i]How to Form an Unbreakable Bond with Your Hounds[scrp=n][algn=0]\r\n\r\nHandlers and trainers of canines refer to this book for techniques to enhance the connection between humans and their hounds. It details training methods and rituals that ensure obedience and loyalty.':
        '[algn=2][scrp=i]Köpeklerinizle Kopmaz Bir Bağ Nasıl Kurulur[scrp=n][algn=0]\r\n\r\nKöpek bakıcıları ve eğitmenleri, insanla köpeği arasındaki bağı güçlendiren teknikler için bu kitaba başvurur. İtaati ve sadakati sağlayan eğitim yöntemlerini ve ayinleri ayrıntısıyla anlatıyor.',

    # ---------------- exanima02: Corlian'in gunlugu ----------------
    "That idiot and his thugs are still sending many down here. I must admit I am impressed by his methods, in some ways he is less a fool than he appears. I must take advantage of this and resume my research while I still can. I've yet to find a place where I w-":
        'O budala ve adamları buraya hâlâ çok sayıda insan yolluyor. İtiraf etmeliyim, yöntemleri beni etkiledi; bazı bakımlardan göründüğü kadar ahmak değil. Bundan yararlanıp hâlâ gücüm varken araştırmama dönmeliyim. Henüz kendimi güvende hissed-',
    "I have been informed that the conservers have spies amongst us. Despite our differences I cannot imagine that they're looking to harm us, or even impede our mission here. I cannot in truth see much reason to prevent them from knowing of our progress, I am inclined to just let them get their information rather than waste resources and encourage doubt and suspicion amongst us.":
        'Koruyucuların aramızda casusları olduğu bana bildirildi. Aramızdaki ayrılıklara karşın bize zarar vermeyi, hatta buradaki görevimizi engellemeyi istediklerini düşünemiyorum. Doğrusu ilerlememizi öğrenmelerini engellemek için pek bir neden göremiyorum; kaynak harcayıp aramızda kuşku ve şüphe büyütmektense bilgilerini almalarına göz yummaya meyilliyim.',
    'This place begins to intrigue me. Thaven understands more things than I imagined. What if he is right? It would change everything. How could we be so ignorant? If I had more time I believe I would undertake his mission. I wonder what changes he has brought about by now with these discoveries. These are important times, I would live to see them.':
        'Burası ilgimi çekmeye başladı. Thaven sandığımdan çok şeyi anlıyor. Ya haklıysa? Bu her şeyi değiştirir. Nasıl bu kadar bilgisiz olabildik? Daha çok zamanım olsaydı, onun görevini üstlenirdim sanırım. Bu keşiflerle şimdiye dek ne değişiklikler yapmıştır acaba. Bunlar önemli zamanlar; görecek kadar yaşamak isterdim.',
    "I'm sitting in a tavern, something I have not done a long time. Alas it is quite empty and all the drink has spoiled long ago.\r\n\r\n\r\nThese people cannot have been so different from us. And yet some things are very strange. There are lamps and even fires that never burn out, I do not understand the source of their power. These walls echo with the souls of the long dead but beneath that I sense something else, like a far reaching presence, it is faint but everywhere, and very strange. Could this be the mythical Guardian? Or even Thaven's Spellgiver?":
        "Bir meyhanede oturuyorum; uzun zamandır yapmadığım bir şey. Ne yazık ki bomboş ve içkilerin hepsi çoktan bozulmuş.\r\n\r\n\r\nBu insanlar bizden çok farklı olamaz. Yine de bazı şeyler pek tuhaf. Hiç sönmeyen lambalar, hatta ateşler var; güçlerinin kaynağını anlamıyorum. Bu duvarlar çoktan ölmüşlerin ruhlarıyla çınlıyor, ama bunun altında başka bir şey seziyorum: uzaklara uzanan bir varlık gibi; belli belirsiz ama her yerde ve çok tuhaf. Efsanevi Muhafız bu olabilir mi? Ya da Thaven'ın Büyü Bahşedeni?",
    "I've been avoiding relations with my subjects as it could become a serious impediment to my work. I did not imagine that I would miss human contact so much. Papin could have carried my legacy but I now treasure his company and friendship more than anything. Even so I deeply regret the loss of a lifetime of imparted knowledge and teachings. If I were to succeed poor Papin would never truly have reaped the benefits of his apprenticeship but he accepted this and was always eager and gratef-\r\n\r\n-s too late now, I must not dwell on it any longer.":
        'Deneklerimle ilişki kurmaktan kaçınıyordum; çalışmama ciddi bir engel olabilirdi. İnsan temasını bu kadar özleyeceğimi düşünmemiştim. Papin mirasımı taşıyabilirdi, ama şimdi arkadaşlığına ve dostluğuna her şeyden çok değer veriyorum. Yine de bir ömür boyu aktarılmış bilgi ve öğretilerin yitip gitmesine derinden üzülüyorum. Başarsaydım zavallı Papin çıraklığının meyvesini gerçekten hiç toplayamayacaktı; ama bunu kabullenmişti, hep istekli ve minnet-\r\n\r\n-k artık çok geç, buna daha fazla takılmamalıyım.',
    'I discovered a truly miraculous substance. It produces a faint light and a pungent odour, when I touched it a wound on my hand I acquired during my cuttings healed rapidly. It was astounding. I have experimented with it but so far it has proven ineffective against my illness. If only I could find more. It was well hidden, obviously it is something of great value. I thought perhaps the lamps contained this substance but I was unable to break one open, when I finally removed one from the wall it gradually lost its light.':
        'Gerçekten mucizevi bir madde buldum. Hafif bir ışık ve keskin bir koku yayıyor; ona dokunduğumda kesim sırasında elimde açılan bir yara hızla kapandı. Şaşırtıcıydı. Üzerinde denemeler yaptım, ama şimdilik hastalığıma karşı etkisiz kaldı. Keşke daha fazlasını bulabilsem. İyi gizlenmişti; belli ki büyük değer taşıyor. Belki lambalar bu maddeyi içeriyordur diye düşündüm, ama birini kırıp açamadım; sonunda birini duvardan söktüğümde ışığını yavaş yavaş yitirdi.',
    "Clearly this was once a place of military activity, but who were they fighting? Were we once at war with these people? It would seem we won. How could such events be completely erased from our history? Thaven believes that somewhere down here lies the true source of our power. I cannot make sense of any of this, I wish now that I had been less dismissive of Thaven's theories.":
        "Burası bir zamanlar açıkça bir askerî faaliyet yeriymiş, ama kime karşı savaşıyorlardı? Bir vakitler bu insanlarla savaşta mıydık? Kazanmışa benziyoruz. Böyle olaylar tarihimizden nasıl büsbütün silinebilir? Thaven, gücümüzün asıl kaynağının burada bir yerde yattığına inanıyor. Bunların hiçbirine anlam veremiyorum; keşke Thaven'ın kuramlarını bu kadar hafife almasaydım.",
    'This log is filled with detailed reports of people violating certain rules. Most of these rules are obviously aimed at preventing the entry of intruders. They are strict and elaborate to the point of seeming a product of paranoia.':
        'Bu defter, belirli kuralları çiğneyen kişilere dair ayrıntılı raporlarla dolu. Bu kuralların çoğu açıkça izinsiz girenleri engellemeye yönelik. Öylesine katı ve ayrıntılılar ki bir kuruntunun ürünü gibi duruyorlar.',
    "A mouldy old scroll that's too damaged to read.":
        'Okunamayacak kadar hasarlı, küflü eski bir tomar.',
    "A mouldy old scroll that's too damaged to read.\r\n":
        'Okunamayacak kadar hasarlı, küflü eski bir tomar.\r\n',
    'Old scroll': 'Eski tomar',
    'The Kingdom Beyond': 'Ötedeki Krallık',
    "The Kingdom Beyond by Alisian Dayen.\r\n\r\nIn a brutal battle a knight named Buto is trapped behind enemy lines. He fights valiantly but is overwhelmed and captured. His captors demand strategic information, but his interrogator is kind to him and tries to win him over to their cause. Buto is loyal to his king and will not give them anything of import. In time however a friendship is established between him and his interrogator. One day the interrogator reveals himself as the very king of Buto's captors and tells him that through their exchanges he has learned much to gain an advantage in the war. He offers Buto his freedom, so that he can return to his king and that one day they might meet again in battle. As Buto leaves his prison he sees the people he would assail in a new light and is disheartened, he knows too that he may be received by his own people as a traitor. And so he asks if he can stay and lead a simple life. The king consents, knowing that he will grow to love and cherish his new home and people, a formidable warrior who will rise to protect them.\r\n":
        "Ötedeki Krallık, Alisian Dayen.\r\n\r\nAmansız bir savaşta Buto adlı bir şövalye düşman hattının gerisinde kapana kısılır. Yiğitçe dövüşür ama alt edilip esir alınır. Onu tutanlar askerî bilgi ister; ne var ki sorgucusu ona iyi davranır ve kendi davalarına kazanmaya çalışır. Buto kralına bağlıdır, önemli hiçbir şey vermez. Ama zamanla onunla sorgucusu arasında bir dostluk doğar. Bir gün sorgucu, Buto'yu tutanların kralının ta kendisi olduğunu açıklar ve bu söyleşilerden savaşta üstünlük sağlayacak çok şey öğrendiğini söyler. Buto'ya özgürlüğünü sunar; kralına dönebilsin ve bir gün belki savaş meydanında yeniden karşılaşsınlar diye. Buto zindanından çıkarken saldıracağı insanları yeni bir gözle görür ve içi kararır; ayrıca kendi halkının onu hain sayabileceğini de bilir. Böylece kalıp yalın bir hayat sürebilir mi diye sorar. Kral kabul eder; yeni yurdunu ve halkını sevip bağrına basacağını, onları korumak için ayağa kalkacak yaman bir savaşçı olacağını bilerek.\r\n",
    'A Handbook for Navigators\r\n\r\nThe pages of this book are filled with essential knowledge for plotting your course across unfamiliar lands. It uncovers the art of mapmaking, from the use of compasses to triangulating positions using either the sun, moon, stars, or even simply identifying features in the terrain helping to develop the artistic and technical skills necessary to craft accurate and visually appealing maps. With beautifully detailed illustrations and carefully written instructions, this book would clearly make a useful companion for anyone interested in learning the art of cartography.':
        'Yol Bulucular İçin El Kitabı\r\n\r\nBu kitabın sayfaları, yabancı topraklarda rota çizmek için gereken temel bilgilerle dolu. Haritacılık sanatını açıyor: pusula kullanımından güneş, ay ve yıldızlarla konum kestirmeye, hatta arazideki belirgin öğeleri seçmeye kadar; doğru ve göze hoş gelen haritalar çizmek için gereken sanatsal ve teknik becerileri geliştirmeye yardım ediyor. Güzelce işlenmiş resimleri ve özenle yazılmış yönergeleriyle bu kitap, haritacılığı öğrenmek isteyen herkes için işe yarar bir yoldaş olurdu.',
    'The Art and Science of Mapmaking': 'Haritacılığın Sanatı ve Bilimi',

    # ---------------- exanima03 ----------------
    "A proctor! Just as I feared, and yet I grew complacent. She was well prepared, obviously she had some idea of what to expect, it was only luck that she didn't kill me. I cannot stay here, I must hide and prepare defences. I don't know how I will be able to continue my work. The proctor would have made an excellent subject, a shame I had to kill her so. I will leave her here to impede any who would pursue me.":
        'Bir vekil! Tam da korktuğum gibi, üstelik gevşemiştim. İyi hazırlanmıştı, belli ki ne bekleyeceğine dair bir fikri vardı; beni öldürmemesi yalnızca şans eseri. Burada kalamam, saklanıp savunma hazırlamalıyım. Çalışmamı nasıl sürdürebilirim bilmiyorum. Vekil mükemmel bir denek olurdu; onu böyle öldürmek zorunda kalmam yazık. Peşime düşecekleri oyalamak için onu burada bırakacağım.',
    'One of my subjects found a most remarkable weapon and escaped, making quick work of anything in his path. I was surprised by his ability to guard his mind against me, I tracked his escape for some time but he then completely vanished from my senses. How did he do that? Who is he?':
        'Deneklerimden biri son derece dikkat çekici bir silah bulup kaçtı; yoluna çıkan her şeyi kısa sürede halletti. Zihnini bana karşı koruyabilmesi beni şaşırttı; kaçışını bir süre izledim, ama sonra duyularımdan büsbütün silindi. Bunu nasıl yaptı? Kim bu?',
    'I have found a helmet which blocks my power when I wear it. Perhaps more importantly it shielded me from the noise of other minds, that presence that has haunted me since I came here was gone. Shortly after donning it I fell asleep, I am certain it was not its power that did this but the calm that came over me, I had not slept so well in quite some time. I feel certain now that it is this presence that causes unrest and aggressiveness in my subjects, clearly it is malevolent.':
        'Taktığımda gücümü engelleyen bir miğfer buldum. Belki daha önemlisi, beni öteki zihinlerin gürültüsünden korudu; buraya geldiğimden beri peşimi bırakmayan o varlık yok oldu. Taktıktan az sonra uykuya daldım; bunu yapanın miğferin gücü değil, üzerime çöken dinginlik olduğuna eminim. Uzun zamandır bu kadar iyi uyumamıştım. Artık deneklerimdeki huzursuzluğa ve saldırganlığa yol açanın bu varlık olduğuna eminim; kötücül olduğu apaçık.',
    'I am certain that Zuiek is importing contraband goods. We have searched his lodgings and the glass workshop on several occasions but we never find anything, not even a hiding place he might use. That old toad has been here longer than any of us and he thinks he can outsmart us. I must be missing something, but what?':
        "Zuiek'in kaçak mal getirdiğine eminim. Kaldığı yeri ve cam atölyesini birkaç kez aradık, ama hiçbir şey bulamıyoruz; kullanabileceği bir zula bile. O ihtiyar kurbağa hepimizden uzun süredir burada ve bizi alt edebileceğini sanıyor. Bir şeyi kaçırıyor olmalıyım, ama neyi?",
    'Zuiek,\r\n\r\nAs you know I have placed a very special order with you. Given the significant payment I have given you I expect prompt delivery, why have I yet to hear from you?':
        'Zuiek,\r\n\r\nBildiğin gibi sana çok özel bir sipariş verdim. Sana ödediğim hatırı sayılır para karşılığında ivedi teslimat bekliyorum; neden hâlâ senden haber almadım?',
    'Some of the soldiers are trying to intimidate me into giving them certain items. I made the mistake of trying to explain why we limit their use, clearly they do not agree and now they dislike me more. Should I inform the captain? I see no choice that will not lead me to more trouble.':
        'Askerlerden bazıları beni korkutup belirli eşyaları vermeye zorluyor. Kullanımlarını neden sınırladığımızı anlatmaya kalkma hatasını yaptım; belli ki katılmıyorlar ve şimdi benden daha çok hoşlanmıyorlar. Yüzbaşıya bildirsem mi? Başımı daha büyük derde sokmayacak bir seçenek göremiyorum.',
    'subjects found a most remarkable weapon and escaped, making quick work of anything in his path. I was ':
        'deneklerim son derece dikkat çekici bir silah bulup kaçtı; yoluna çıkan her şeyi çabucak halletti. Ben ',

    # ---------------- exanima04 ----------------
    "What terrible place is this? A thunderous voice shouts unintelligibly in my mind, as though trying to command me with wordless urgency. It's as though it wants to both urge me and sooth me, I am terrified that I may succumb to its will. This strange helm is my only respite, but it leaves me vulnerable.\r\n\r\nThere is also a constant wailing of ancient restless spirits, has this presence been keeping them from finding peace?":
        'Bu ne korkunç yer böyle? Zihnimde gök gürültüsü gibi bir ses anlaşılmaz biçimde bağırıyor; sanki beni sözsüz bir aciliyetle buyruğu altına almaya çalışıyor. Hem beni dürtmek hem de yatıştırmak istiyor gibi; istencine boyun eğmekten dehşete kapılıyorum. Bu tuhaf miğfer tek sığınağım, ama beni savunmasız bırakıyor.\r\n\r\nAyrıca kadim, huzursuz ruhların sürekli bir feryadı var; bu varlık onların huzur bulmasını mı engelliyor?',
    'Dassin, keep a watchful eye over the scribes and the archivists, especially the archivists. There have been many reports of things being taken and hidden away. We must be thorough.':
        'Dassin, kâtipleri ve arşivcileri dikkatle gözle, özellikle arşivcileri. Bir şeylerin alınıp saklandığına dair çok sayıda rapor geldi. Titiz olmalıyız.',
    "Burn, burn it all! A lifetime watching over things that I must now quietly consign to the fires. For what? The teachings of a monstrous traitor? The sorry truth is that no one is willing now to admit they were wrong, too much was invested, it couldn't be for nothing. And so we go forth and burn the path behind us, let blind hope be our guide.":
        'Yak, hepsini yak! Bir ömür boyu gözettiğim şeyleri şimdi sessizce ateşe vermeliyim. Ne uğruna? Canavar bir hainin öğretileri mi? Acı gerçek şu ki artık kimse yanıldığını kabul etmeye yanaşmıyor; çok fazla emek verildi, boşuna olamazdı. Böylece ilerliyor ve ardımızdaki yolu yakıyoruz; bırakın kör umut kılavuzumuz olsun.',
    'Our glorious hero is little more than a killer. Now that his deadly work is done he cares nothing for the consequences. Murder our gods so that we may be free. And lost. I will not forget who saved us from oblivion. We have been warned, far worse is coming and our demise is now inevitable.':
        'Şanlı kahramanımız bir katilden pek farklı değil. Ölümcül işi bittiğine göre sonuçlara hiç aldırmıyor. Özgür olalım diye tanrılarımızı öldürün. Ve yolumuzu şaşıralım. Bizi yokluktan kimin kurtardığını unutmayacağım. Uyarıldık: çok daha kötüsü geliyor ve sonumuz artık kaçınılmaz.',
    'Venerable Aderon, \r\n\r\nI understand that you are conflicted, but I must ask that you keep the voicing of your misgivings to within the council. You cannot hope to stop this now, you will only cause disquiet and potentially worse. Please, remember the responsibility that comes with your position.\r\n\r\nTerschenn':
        'Muhterem Aderon, \r\n\r\nİkilemde olduğunuzu anlıyorum, ama kaygılarınızı dile getirmeyi meclisle sınırlı tutmanızı rica etmeliyim. Bunu artık durdurmayı umamazsınız; yalnızca huzursuzluğa, belki daha kötüsüne yol açarsınız. Lütfen, konumunuzun getirdiği sorumluluğu anımsayın.\r\n\r\nTerschenn',
    "I have never been so terrified. I was attacked by a huge dreadful creature. A demon perhaps? I tried to control it, but though its mind felt completely unguarded, it was oblivious to my intrusion. I was only able to confuse it briefly and get away, I am defenceless against this thing. I dare not venture out again.\r\n\r\nThese dead guards, perhaps I could call them to action. I don't imagine they could do much against such a monster, but the distraction might cover my escape.":
        'Hiç bu kadar dehşete kapılmamıştım. Kocaman, korkunç bir yaratık bana saldırdı. Belki bir iblis? Onu denetlemeye çalıştım; zihni tümüyle korumasız hissedilse de girişimimin farkına bile varmadı. Ancak kısa süre şaşırtıp kaçabildim; bu şeye karşı savunmasızım. Bir daha dışarı çıkmaya cesaret edemiyorum.\r\n\r\nŞu ölü muhafızlar, belki onları göreve çağırabilirim. Böyle bir canavara karşı çok şey yapabileceklerini sanmıyorum, ama yaratacakları oyalama kaçışımı örtebilir.',
    'When I took this oath I told myself my life no longer mattered. Now that courage, that sense of purpose, is fading fast. I look to the others for strength, but I find the same doubt in their eyes. They mocked us and now I see the truth of it. This is senseless.':
        'Bu andı içerken kendime hayatımın artık önemi olmadığını söylemiştim. Şimdi o cesaret, o amaç duygusu hızla sönüyor. Güç bulmak için ötekilere bakıyorum, ama gözlerinde aynı kuşkuyu görüyorum. Bizimle alay ettiler; şimdi bunun doğruluğunu anlıyorum. Bunun bir anlamı yok.',
    "I fear I don't have long left. I have abandoned my efforts to escape death. It was foolish, and yet I have accomplished so much. I must try to send word to Thaven, he will see the importance of my work, even though he is concerned with other matters.\r\n\r\nI believed Thaven's pursuits to be as hollow as my own, a stubborn refusal to accept bitter truths. After what I've seen here anything seems possible. I will spend the rest of my days discovering what I can, I can still be of help.":
        "Korkarım fazla vaktim kalmadı. Ölümden kaçma çabalarımdan vazgeçtim. Ahmakçaydı, yine de çok şey başardım. Thaven'a haber ulaştırmaya çalışmalıyım; başka işlerle uğraşsa da çalışmamın önemini görecektir.\r\n\r\nThaven'ın peşinde koştuklarının da benimkiler kadar boş olduğunu, acı gerçekleri kabul etmemekte inatlaşmak olduğunu sanırdım. Burada gördüklerimden sonra her şey mümkün görünüyor. Kalan günlerimi elimden geldiğince keşfetmeye ayıracağım; hâlâ bir yardımım dokunabilir.",
    "Venerable Kaeylen,\r\n\r\nForgive me if I speak so directly, but I won't hold my tongue given what I'm witness to. It cannot be what you intended, they are taking and burning everything! We will be left completely in the dark of our past, our mistakes, the threats that we've yet to face. No good can come of this, and those who bring it about seek only to rule absolute through the power of ignorance.\r\n\r\nI implore you to see the fault in this and put an end to it. This is not how we embark on a new path, we head towards nothing but our ultimate demise.\r\n\r\nYour humble servant,\r\nAderon":
        'Muhterem Kaeylen,\r\n\r\nBu denli dobra konuştuğum için bağışlayın, ama tanık olduklarım karşısında dilimi tutamam. Bu sizin istediğiniz olamaz; her şeyi alıp yakıyorlar! Geçmişimiz, hatalarımız ve henüz karşılaşmadığımız tehditler konusunda büsbütün karanlıkta kalacağız. Bundan hayır gelmez; bunu yapanlar yalnızca bilgisizliğin gücüyle mutlak biçimde hükmetmek istiyor.\r\n\r\nBundaki yanlışı görmeniz ve buna son vermeniz için yalvarıyorum. Yeni bir yola böyle çıkılmaz; nihai yıkımımızdan başka bir yere gitmiyoruz.\r\n\r\nAlçakgönüllü hizmetkârınız,\r\nAderon',
    'Orenn,\r\n\r\nI commend you for intercepting this correspondence, you have been of great service.\r\n\r\nIt pains me to see him so misguided, his only fault is to believe too strongly in the quality of our spirit. This delusion of his and his very conviction is too dangerous, we cannot risk the harm he would do if he were to infect others with his ideas.\r\n\r\nMy heart is heavy with the burden of it, but I must ask that y-':
        'Orenn,\r\n\r\nBu yazışmayı ele geçirdiğin için seni takdir ediyorum; büyük hizmette bulundun.\r\n\r\nOnu bu denli yoldan çıkmış görmek bana acı veriyor; tek kusuru ruhumuzun niteliğine fazlaca güçlü inanması. Bu kuruntusu ve işte bu kesin inancı çok tehlikeli; düşüncelerini başkalarına bulaştırırsa vereceği zararı göze alamayız.\r\n\r\nYüreğim bunun yüküyle ağır, ama senden şunu ist-',

    # ---------------- exanima05 ----------------
    'That silly nurse touching everything! She accidentally opened my secret study. All I could think to do is send her away in a hurry. I think she may have gotten entirely the wrong idea.':
        'O akılsız hemşire her şeye dokunuyor! Kazara gizli çalışma odamı açtı. Aklıma yalnızca onu apar topar başımdan savmak geldi. Sanırım büsbütün yanlış bir fikre kapılmış olabilir.',
    "Who needs The Guardian when you have the great Torris? What do I expect? To be hailed as a hero? If they knew what I attempted, they'd have my head.":
        "Ulu Torris varken Muhafız'a ne gerek var? Ne bekliyorum ki? Kahraman ilan edilmeyi mi? Neye kalkıştığımı bilseler, kellemi alırlardı.",
    'I have no more time, and find I cannot leave without knowing. I will give my life, nothing else matters to me now.\r\n\r\nI was not able to acquire a stronger source of power, so I must be quick. Should I disappear forever behind this wall, then perhaps at least I will be remembered as the good physician, and not the madman.':
        'Vaktim kalmadı ve bilmeden gidemeyeceğimi görüyorum. Canımı vereceğim; artık başka hiçbir şeyin önemi yok.\r\n\r\nDaha güçlü bir güç kaynağı edinemedim, bu yüzden çabuk olmalıyım. Bu duvarın ardında sonsuza dek yok olursam, bari iyi hekim olarak anılırım, deli olarak değil.',
    "With breaths held we tread\r\nYou and me, hand in hand\r\nOur gazes locked ahead\r\nUpon this endless land\r\n\r\nWhere rivers flow\r\nUnder open skies\r\nAnd slow they grow\r\nBut trees reach high\r\nThe beasts run wild\r\nWe'll hunt, and after\r\nWe'll make a child\r\nTo raise with laughter":
        'Soluğumuzu tutup yürürüz\r\nSen ve ben, el ele\r\nGözlerimiz hep ileride\r\nBu bitmeyen toprakta\r\n\r\nIrmakların aktığı\r\nAçık göklerin altında\r\nAğır ağır büyürler\r\nAma ağaçlar göğe uzanır\r\nYabanıl koşar hayvanlar\r\nAvlanırız, ardından\r\nBir çocuk yaparız\r\nKahkahayla büyütmeye',
    "I've finally received a reply from Thaven, and I regret that I wrote to him. We all know what he did, we all know what he's capable of. I can't trust him, if he's sending someone to me, I fear it will not be with good intentions.":
        "Sonunda Thaven'dan yanıt aldım ve ona yazdığıma pişmanım. Ne yaptığını hepimiz biliyoruz, nelere kadir olduğunu da. Ona güvenemem; bana birini yolluyorsa, korkarım niyeti iyi olmayacak.",
    'Dearest Corlian,\r\n\r\nIt is good to hear from you my old friend. I heard what had befallen you, but I knew you would not be so easily thwarted.\r\n\r\nI am terribly sorry about Papin, I cannot imagine what a loss it is for you. I am sending someone to help you. I know you well, and I believe you will be greatly attuned.\r\n\r\nOh, the things we are discovering! I find myself struggling to keep to my purpose. It seems my theories were correct, but there is so much more to learn, so much I would never have guessed. I cannot wait to hear what a man with your insight has uncovered.\r\n\r\nBe well my friend, I hope to see you soon.\r\n\r\nThaven':
        'Sevgili Corlian,\r\n\r\nSenden haber almak güzel eski dostum. Başına gelenleri duydum, ama bu kadar kolay yıldırılmayacağını biliyordum.\r\n\r\nPapin için çok üzgünüm; senin için ne büyük bir kayıp olduğunu hayal bile edemem. Sana yardım etmesi için birini yolluyorum. Seni iyi tanırım ve onunla fazlasıyla uyumlu olacağına inanıyorum.\r\n\r\nAh, keşfettiğimiz şeyler! Kendi amacıma bağlı kalmakta zorlanıyorum. Anlaşılan kuramlarım doğruymuş, ama öğrenilecek o kadar çok şey var ki; hiç tahmin edemeyeceğim kadar. Senin gibi kavrayışlı bir adamın neler bulduğunu duymak için sabırsızlanıyorum.\r\n\r\nSağlıcakla kal dostum, umarım yakında görüşürüz.\r\n\r\nThaven',
    "A book containing a great many recipes for mixtures, salves and unguents. They seem to be all targeted at curing conditions that you've never heard of.":
        'Karışımlar, merhemler ve yağlar için pek çok tarif içeren bir kitap. Hepsi, adını hiç duymadığın rahatsızlıkları iyileştirmeye yönelik görünüyor.',
    "The situation is getting worse, now everyone seems to be amassing weapons and other combat gear. They fear that there will be violence, and want to be prepared. These items are being traded everywhere in secret, including some of our own equipment, which is greatly concerning. If someone were to impersonate the law they could cause some serious damage, and no doubt I'd be held responsible.":
        'Durum kötüleşiyor; artık herkes silah ve dövüş donanımı yığıyor gibi. Şiddet çıkacağından korkuyorlar ve hazırlıklı olmak istiyorlar. Bu eşyalar her yerde gizlice alınıp satılıyor; içlerinde bizim teçhizatımızdan bazıları da var ki bu son derece kaygı verici. Biri kanun adamı taklidi yaparsa ciddi zarar verebilir ve kuşkusuz sorumlu ben tutulurum.',
    "As we are now invaded, I have asked my assistant to bring me what bodies of the creatures he can. I believe that through dissection I may be able to discover some weakness, some way we might combat them more effectively.\r\n\r\n\r\nI have made a very strange discovery, through an upsetting accident. I found a kind of gland, filled with a highly adhesive fluid. It made contact with my hand, and within a short period of time the skin on my arm has changed. It has become tough, almost scaly. I am hoping the effect will wear off with time.\r\n\r\n\r\nIt has been several days and my skin has not improved. I've consulted the physician Theris, we've come to the conclusion that it must be an altering agent, changing the structure and function of living tissues it contacts.\r\n\r\nTheris wants to know more, and we've decided to test small doses on those in his care who do not have long to live. I will persuade Elko to go below and fetch more, where many of the creatures can now be found.\r\n\r\n\r\nThe glands seem to have many varied effects! In some subjects we noticed nothing but mild disfiguration, sometimes with mild adverse effects, but in others we've noticed such things as an increase in strength, or a capacity for more rapid movements. The changes are small, so we cannot be certain, more tests are needed.\r\n\r\n\r\nWe've now had two serious accidents and we must stop. We noticed some fleeting changes in behaviour, but now we've had a second subject lose all reason and suddenly act as a trapped animal.":
        "Artık istilaya uğradığımıza göre, yardımcımdan yaratıkların bulabildiği kadar cesedini getirmesini istedim. Kesip inceleyerek bir zayıflık, onlarla daha etkili savaşmanın bir yolunu bulabileceğime inanıyorum.\r\n\r\n\r\nCanımı sıkan bir kaza sonucu çok tuhaf bir keşif yaptım. Son derece yapışkan bir sıvıyla dolu bir tür bez buldum. Elime değdi ve kısa süre içinde kolumdaki deri değişti. Sertleşti, neredeyse pullandı. Umarım etki zamanla geçer.\r\n\r\n\r\nBirkaç gün geçti ve derim düzelmedi. Hekim Theris'e danıştım; bunun, dokunduğu canlı dokunun yapısını ve işleyişini değiştiren bir dönüştürücü olması gerektiği sonucuna vardık.\r\n\r\nTheris daha fazlasını öğrenmek istiyor ve bakımındaki, ömrü uzun olmayan kişilerde küçük dozlar denemeye karar verdik. Elko'yu aşağı inip daha fazla getirmeye ikna edeceğim; yaratıkların çoğu artık orada bulunabiliyor.\r\n\r\n\r\nBezlerin pek çok değişik etkisi var! Bazı deneklerde hafif bir biçim bozukluğundan, kimi zaman hafif olumsuz etkilerden başka bir şey görmedik; ama bazılarında güç artışı ya da daha hızlı hareket edebilme gibi şeyler gözledik. Değişimler küçük olduğundan emin olamıyoruz, daha çok deney gerek.\r\n\r\n\r\nİki ciddi kaza yaşadık ve durmalıyız. Davranışta geçici değişiklikler fark etmiştik, ama şimdi ikinci bir denek tüm aklını yitirip birdenbire kapana kısılmış bir hayvan gibi davrandı.",
    'Captain Renis,\r\n\r\nI have received your initial report. I appreciate that you did not try to draw conclusions, but it is clear that the intent of the transgression was to sell crystals that would go unused by means of the device. In response to this the supply of crystals will be more strictly regulated. Every use and transport must be logged and new crystals will not be supplied until exhausted ones have been returned in parity.\r\n\r\nIt is requested that you further question your men based on this information and see if potential buyers had already been approached and if they can be identified.\r\n\r\nI await further communications.\r\n\r\nSupervisor Seredin\r\n':
        'Yüzbaşı Renis,\r\n\r\nİlk raporunuzu aldım. Sonuç çıkarmaya kalkışmamanızı takdir ediyorum, ama suçun amacının, aygıt sayesinde kullanılmadan artacak kristalleri satmak olduğu açık. Buna karşılık kristal tedariki daha sıkı düzenlenecek. Her kullanım ve nakil kayda geçirilmeli; tükenmiş kristaller birebir iade edilmeden yenisi verilmeyecek.\r\n\r\nBu bilgiye dayanarak adamlarınızı yeniden sorgulamanız, olası alıcılara daha önce yaklaşılıp yaklaşılmadığını ve kimliklerinin saptanıp saptanamayacağını öğrenmeniz isteniyor.\r\n\r\nYeni bildirimlerinizi bekliyorum.\r\n\r\nDenetmen Seredin\r\n',
    "Captain Renis,\r\n\r\nI write in regard to the recent incident with your missing guards. There will be inquiries about discipline, but for now all efforts should be directed at finding out where the device comes from and who made it. They believe the device has origins within your jurisdiction. You will be leading the investigation as you are deemed best equipped to do so. This is a matter of the highest priority. The item will be left with you for the purpose of your investigation. Guard it well, it is extremely dangerous. I cannot stress this enough.\r\n\r\nSomeone should have already come to reclaim the crystal by now. Do not concern yourself with the provenance of that, it will be handled internally.\r\n\r\nThey expect a prompt report on the interrogation of your men. Don't be surprised if someone comes in to follow up on this and conducts further interrogations. It is assumed that you have suitable people in place who can ask the right questions about the origin of the device. If you do not, let me know and I will put you in contact with an agent of my own.\r\n\r\nBe sure that if you uncover any item of a similar construction or any information you may deem pertinent you report on it immediately. I don't think I need to tell you to take no action, but only communicate your findings.\r\n\r\nSupervisor Seredin":
        'Yüzbaşı Renis,\r\n\r\nKayıp muhafızlarınızla ilgili son olay hakkında yazıyorum. Disiplin soruşturmaları olacak, ama şimdilik tüm çaba aygıtın nereden geldiğini ve onu kimin yaptığını bulmaya yönelmeli. Aygıtın kökeninin sizin yetki alanınızda olduğuna inanıyorlar. Bu iş için en donanımlı kişi sayıldığınızdan soruşturmayı siz yürüteceksiniz. Bu, en yüksek öncelikli bir konudur. Soruşturmanız için nesne sizde bırakılacak. İyi koruyun, son derece tehlikelidir. Bunu ne kadar vurgulasam az.\r\n\r\nKristali geri almaya birinin çoktan gelmiş olması gerekirdi. Onun kaynağıyla ilgilenmeyin, o iş içeride halledilecek.\r\n\r\nAdamlarınızın sorgusuna dair ivedi bir rapor bekliyorlar. Birinin gelip bunu takip etmesine ve yeni sorgular yapmasına şaşırmayın. Aygıtın kökeni hakkında doğru soruları sorabilecek uygun kişilerin elinizde olduğu varsayılıyor. Yoksa bana bildirin, sizi kendi adamlarımdan biriyle görüştüreyim.\r\n\r\nBenzer yapıda bir nesne ya da yerinde göreceğiniz bir bilgi ortaya çıkarırsanız hemen bildirin. Hiçbir işleme girişmemenizi, yalnızca bulgularınızı iletmenizi söylememe gerek yok sanırım.\r\n\r\nDenetmen Seredin',

    # ---------------- exanima06 ----------------
    'A group must have stayed in hiding, and once we were almost all gone they raided the armouries. I assume they killed an officer to gain access. Many were killed, but our attempts to stop them were ultimately futile. I was backed into this room and they blocked the door. They did not see I was carrying this mask.':
        'Bir grup saklanmayı sürdürmüş olmalı; neredeyse hepimiz gittikten sonra cephanelikleri bastılar. Girmek için bir subayı öldürdüklerini sanıyorum. Çok kişi öldü, ama onları durdurma çabalarımız sonuçta boşa çıktı. Bu odaya sıkıştırıldım ve kapıyı kapattılar. Bu maskeyi taşıdığımı görmediler.',
    "It has been some time now, I don't know how long. I don't think anyone will come for me. Are the other all dead? This mask will sustain me for some time, but I fear it will only prolongue my suffering.":
        'Bir süre oldu, ne kadar bilmiyorum. Kimsenin benim için geleceğini sanmıyorum. Ötekilerin hepsi öldü mü? Bu maske beni bir süre ayakta tutar, ama korkarım yalnızca çektiğim acıyı uzatacak.',
    'These golems have proven an impassable barrier for me, I must turn back. I was shocked and dismayed to see them animate. At first I thought them to be lifeless constructs, a product of magics that I cannot fathom, and yet I sense something from them. Being versed in necromancy as I am, I fear these may be the result of something horrible, far worse than the practices of my art.\r\n\r\nWhat if all that I see here is explained by the harvesting souls as a source of power? Minds reduced and locked in the eternal torment of serving some mundane purpose. The notion is frightful.':
        'Bu golemler benim için aşılmaz bir engel oldu, geri dönmeliyim. Onların canlandığını görmek beni sarstı ve dehşete düşürdü. Önce cansız yapılar, kavrayamadığım bir büyünün ürünü sandım; yine de onlardan bir şey seziyorum. Nekromantlıkta uzman biri olarak, bunların korkunç bir şeyin, kendi sanatımın uygulamalarından çok daha beterinin sonucu olabileceğinden korkuyorum.\r\n\r\nYa burada gördüğüm her şeyin açıklaması, ruhların güç kaynağı olarak hasat edilmesiyse? Küçültülmüş ve sıradan bir amaca hizmet etmenin sonsuz azabına kilitlenmiş zihinler. Bu düşünce ürkütücü.',
    "I feel almost certain that Spellgiver and Corruptor are one and the same, condemned for atrocities, corrupting mortal souls. If this is true then Thaven's quest is folly. We did well to refuse our past and abandon such dark practices. I would hope that Thaven too might reach this conclusion, but I fear otherwise, and that he must be stopped. I now regret having sent word to him, he cannot save me anyway.":
        "Büyü Bahşeden ile Yozlaştıran'ın aynı kişi olduğuna neredeyse eminim: zulümleri, ölümlü ruhları yozlaştırdığı için lanetlenmiş biri. Bu doğruysa Thaven'ın arayışı bir çılgınlık. Geçmişimizi reddedip böyle karanlık uygulamaları bırakmakla iyi etmişiz. Thaven'ın da bu sonuca varmasını umardım, ama korkarım varmayacak ve durdurulması gerekecek. Ona haber yolladığıma şimdi pişmanım; zaten beni kurtaramaz.",
    "Many now come to our doors. I suppose they wish to be prepared for what's ahead. It is good to see fresh blood, but I am concerned by the implications of their selfish purpose. That is not what we're here for.":
        'Artık çok kişi kapımıza geliyor. Sanırım önlerindekine hazır olmak istiyorlar. Taze kan görmek güzel, ama bencil amaçlarının anlamı beni kaygılandırıyor. Biz bunun için burada değiliz.',
    "I woke to terrible screams. Who could sleep through that? Edrian, my neighbour, was never found. All that's left of him is the blood in his bathroom. They say they are now amongst us. How could this happen? There are rumors that they were let through deliberately, but I cannot believe that.":
        'Korkunç çığlıklarla uyandım. Kim uyuyabilir ki öyle bir şeyde? Komşum Edrian hiç bulunamadı. Ondan geriye yalnızca banyosundaki kan kaldı. Artık aramızda olduklarını söylüyorlar. Bu nasıl olabildi? Bilerek içeri alındıklarına dair söylentiler var, ama buna inanamıyorum.',
    'It will be good to leave here, start anew. I feel torn between two worlds, and responsible for things that are beyond me. I have blindly deferred to the judgement of others, and just as blindly enforced their will. I find that I have no opinion of my own, I see no atrocities committed, no teachings imparted, just empty words and stubborn egos. How can we judge such things? Yes, I am eager to leave it all behind.':
        'Buradan ayrılmak, yeniden başlamak iyi olacak. Kendimi iki dünya arasında bölünmüş, üstelik beni aşan şeylerden sorumlu hissediyorum. Körü körüne başkalarının yargısına boyun eğdim ve aynı körlükle istençlerini uyguladım. Kendime ait bir görüşüm olmadığını görüyorum; işlenmiş bir zulüm de görmüyorum, aktarılmış bir öğreti de; yalnızca boş sözler ve inatçı benlikler. Böyle şeyleri nasıl yargılayabiliriz? Evet, hepsini geride bırakmak için sabırsızım.',
    'This appears to have been an alchemical treatise holding many recipes for the transmutation of materials and producing magical effects. A great many of its pages seem to have been torn out in a terrible hurry. What is left is written in words that are mostly beyond your comprehension.':
        'Bu, maddelerin dönüştürülmesine ve büyülü etkiler üretmeye dair pek çok tarif içeren bir simya incelemesi gibi görünüyor. Sayfalarının büyük bölümü korkunç bir telaşla koparılmış. Geriye kalanlar, çoğu kavrayışının ötesinde sözcüklerle yazılmış.',

    # ---------------- exanima07 ----------------
    "[scrp=i]I'm sorry Stenris, but I'm going to leave the company.\r\n\r\nThis is not what we do. We challenged the mind, we asked the questions! Look at us now, acting out badly written lies, pretending nothing's wrong. I know you are being pressured, and probably under threat, but it is too much to bear. I used to be proud of what we do, but now all I feel as I stand on our stage is shame. I won't do it anymore.\r\n\r\nI will seek other ways to reach people, perhaps I'll join the fight. I hope that you can find peace when this is all over.\r\n\r\nYour friend who begs you will forgive him,\r\nAthelin":
        '[scrp=i]Üzgünüm Stenris, ama topluluktan ayrılıyorum.\r\n\r\nBizim işimiz bu değil. Zihni sorgulardık, soruları biz sorardık! Şimdi hâlimize bak: kötü yazılmış yalanları oynuyor, hiçbir şey yokmuş gibi yapıyoruz. Baskı altında, belki de tehdit altında olduğunu biliyorum, ama bu taşınacak gibi değil. Eskiden yaptığımız işle gurur duyardım; şimdi sahnemizde dururken tek hissettiğim utanç. Artık yapmayacağım.\r\n\r\nİnsanlara ulaşmanın başka yollarını arayacağım, belki mücadeleye katılırım. Bütün bunlar bittiğinde huzur bulabilmeni dilerim.\r\n\r\nSeni bağışlaman için yalvaran dostun,\r\nAthelin',
    "[scrp=i]Methis gave me and some others these rods. He says they're useless on their own, and he made us each swear to keep our rod and its crystal safe. If we're to find ourselves in danger and with no escape, then we should gather all in the same place, surround it with the rods and wait for help. He's not said much more, but we trust him well. I'll do my part.":
        '[scrp=i]Methis bana ve birkaç kişiye bu çubukları verdi. Tek başlarına işe yaramadıklarını söylüyor ve her birimize çubuğumuzu ve kristalini korumaya yemin ettirdi. Tehlikeye düşer ve kaçış bulamazsak, hepimiz aynı yerde toplanıp orayı çubuklarla çevirmeli ve yardım beklemeliyiz. Fazla bir şey söylemedi, ama ona iyice güveniyoruz. Ben üzerime düşeni yaparım.',
    "[scrp=i]Dear Themin,\r\n\r\nI hope this letter finds you well and whole. I have heard of your foolhardy endeavours. Always a champion of the common people.\r\n\r\nI am due to leave with the next group in five days. I would have sought you out, but with everything that's happening I had to settle for this letter. I hope to see you again soon, please do not risk everything for this dying city. \r\n\r\nI would have left word either way, but I'm afraid I must also warn you of a great danger. Amatine claims to have someone who can truly wake the sentries, and he intends to do it. You must stop him, no one else has the authority. If he is not stopped we will have another great threat upon us.\r\n\r\nYours,\r\nElenis":
        '[scrp=i]Sevgili Themin,\r\n\r\nUmarım bu mektup seni sağ salim bulur. Gözü kara girişimlerini duydum. Hep sıradan halkın savunucusu.\r\n\r\nBeş gün sonra bir sonraki kafileyle ayrılacağım. Seni arardım, ama olan biten her şeyin ortasında bu mektupla yetinmek zorunda kaldım. Umarım yakında yine görüşürüz; lütfen ölmekte olan bu şehir için her şeyini tehlikeye atma. \r\n\r\nHer hâlükârda haber bırakırdım, ama korkarım seni büyük bir tehlikeye karşı da uyarmalıyım. Amatine, nöbetçileri gerçekten uyandırabilecek birini bulduğunu öne sürüyor ve bunu yapmaya niyetli. Onu durdurmalısın; başka kimsenin yetkisi yok. Durdurulmazsa başımıza bir büyük tehdit daha gelecek.\r\n\r\nSenin,\r\nElenis',

    # ---------------- exanima08 ----------------
    "Thaven's lackey has reached me. {®Exanima.Unknown.HeShe} is not a bad sort, and a strong mind too. I do not sense nefarious intent, Thaven's offer of help at least seems true. It is strange to find some companionship after all this strife, the death of Papin and my own life slipping away spurred me into a compulsion to do something before the end, I never stopped to consider my actions. I hurt so many, and buried my guilt along with my grief. ":
        "Thaven'ın adamı bana ulaştı. {®Exanima.Unknown.HeShe} fena biri değil, üstelik güçlü bir zihni de var. Kötü bir niyet sezmiyorum; Thaven'ın yardım önerisi hiç değilse gerçek görünüyor. Bunca çekişmeden sonra bir arkadaşlık bulmak tuhaf. Papin'in ölümü ve kendi hayatımın elimden kayıp gitmesi, sondan önce bir şey yapma saplantısına sürükledi beni; eylemlerimi düşünmek için hiç durmadım. Çok kişiyi incittim ve suçluluğumu kederimle birlikte gömdüm. ",
    "I have encountered multiple times dead that were not raised by me. At first I thought I was forgetful, then I feared a necromancer with a talent to match my own was near. I wondered even if the fanciful myths of a Guardian who rules the dead could hold some truth. Now I am beset by a frightful notion, what if the dead, once awoken so, call to each other? Could it be a thing that spreads as does a plague? What if this is an art not merely forgotten and shunned by those of sensitive natures, but willfully concealed and forbidden for what it might do if left unchecked? Have I set something terrible in motion?\r\n\r\nI wish it were not so, but I feel it is true. Is this to be my own fate as well? I will not let it be, I must find a way to escape this mortal shell, even if into oblivion. Perhaps if I truly succeed, I can undo some of the damage I've wrought.":
        "Birçok kez, benim diriltmediğim ölülerle karşılaştım. Önce unutkanlık sandım, sonra benimkine denk yetenekte bir nekromantın yakınlarda olmasından korktum. Hatta ölülere hükmeden bir Muhafız'a dair hayalî efsanelerde bir doğruluk payı olabilir mi diye düşündüm. Şimdi ürkütücü bir düşünce sardı beni: ya ölüler, böyle bir kez uyandırıldıklarında birbirlerini çağırıyorsa? Bu, veba gibi yayılan bir şey olabilir mi? Ya bu sanat, yalnızca unutulmuş ve ince ruhluların uzak durduğu bir şey değil de, başıboş bırakılırsa yapabilecekleri yüzünden bilerek gizlenmiş ve yasaklanmışsa? Korkunç bir şeyi mi başlattım?\r\n\r\nKeşke öyle olmasa, ama doğru olduğunu hissediyorum. Bu benim de kaderim mi olacak? Buna izin vermeyeceğim; bu ölümlü kabuktan kaçmanın bir yolunu bulmalıyım, yokluğa açılsa bile. Belki gerçekten başarırsam, verdiğim zararın bir kısmını geri alabilirim.",
    'The Ways of the Thaumaturge - Part 1': 'Tömaturjistin Yolları - Bölüm 1',
    'A book that introduces many concepts on the working of the thaumaturgic mind and presents various notions that seem at times in conflict and of little substance. Your impression is that the author was well informed, but did not truly understand what was divulged.\r\n\r\nThaumaturges are known to dwell in lonely towers and other remote residences. A common misconception is that it is to conduct their strange work away from prying eyes, but the truth is less sinister and less obvious. The mind of a thaumaturge is an intangible thing that extends far beyond their physical presence, it is as a great tree of connections to the world around them. When the lesser minds of multitudes move through this time and time again, they slowly chip away at its branches, weakening the thaumaturge as they do so. This is why they withdraw from company and seek isolation, so that their power is not drained away.\r\n\r\nA notable exception to this are the great healers, they who live selflessly among those to which they might lend aid. The uncomfortable substance of their success is that as they care for those whom from illness pass to death, they form a bond, and from that bond, in the moment of passing, they take something to sustain them. This is little known and little discussed, as it could be seen in the wrong light and cast suspicion on these devoted servants of the community.':
        'Tömaturji zihninin işleyişine dair pek çok kavramı tanıtan, yer yer birbiriyle çelişen ve pek de sağlam durmayan görüşler sunan bir kitap. İzlenimin, yazarın bilgili olduğu ama kendisine açıklananları gerçekten anlamadığı yönünde.\r\n\r\nTömaturjistlerin ıssız kulelerde ve uzak konaklarda yaşadığı bilinir. Yaygın bir yanılgı, bunun tuhaf işlerini meraklı gözlerden uzakta yürütmek için olduğudur; oysa gerçek daha az uğursuz ve daha az açıktır. Bir tömaturjistin zihni, fiziksel varlığının çok ötesine uzanan elle tutulmaz bir şeydir; çevresindeki dünyaya uzanan bağlantılardan oluşan koca bir ağaç gibidir. Kalabalıkların küçük zihinleri bunun içinden defalarca geçtiğinde, dallarını yavaş yavaş yontar ve bunu yaparken tömaturjisti zayıflatır. İşte bu yüzden topluluktan çekilir, yalnızlığı ararlar; güçleri boşa akmasın diye.\r\n\r\nBunun dikkate değer bir istisnası büyük şifacılardır; yardım edebilecekleri kimselerin arasında özverili biçimde yaşayanlar. Başarılarının rahatsız edici özü şudur: hastalıktan ölüme geçenlere bakarken bir bağ kurarlar ve o bağdan, geçiş anında, kendilerini ayakta tutacak bir şey alırlar. Bu az bilinir ve az konuşulur; çünkü yanlış anlaşılabilir ve topluluğun bu adanmış hizmetkârlarına kuşku düşürebilir.',
    'Torn Page': 'Yırtık Sayfa',
    "Sashya said I am the most devoted wife she ever did meet. I give give give, he takes takes takes, she told me. I laughed and told her to hush, but I must admit the conversation left me with an uneasy feeling. It reminded me of the same old question I've been asking all these years. Why does he spend so much time alone in his blasted study? What does he do in there? Suspicion overcomes me at times. He is so evasive when questioned about it. I know he has secrets there, I just know it. I suppress my curiosity, as a dutiful wife must, but I do so wish he wouldn't keep things from me! I suppose I must accept I shall never know my husband fully, perhaps all men are this way...":
        'Sashya, gördüğü en fedakâr eş olduğumu söyledi. Ben verir de veririm, o alır da alır, dedi. Güldüm ve sus dedim, ama itiraf etmeliyim, bu konuşma içimde tedirgin bir his bıraktı. Yıllardır sorup durduğum aynı eski soruyu anımsattı bana. Neden o lanet çalışma odasında bu kadar çok zaman yalnız geçiriyor? Orada ne yapıyor? Zaman zaman kuşku beni ele geçiriyor. Sorulduğunda öyle kaçamak davranıyor ki. Orada sırları olduğunu biliyorum, biliyorum işte. Vazifeşinas bir eşin yapması gerektiği gibi merakımı bastırıyorum, ama keşke benden bir şey saklamasa! Sanırım kocamı hiçbir zaman tümüyle tanıyamayacağımı kabullenmeliyim; belki tüm erkekler böyledir...',
    'My work is near complete, I believe it will serve, but for this first vessel to come alive and be told to do as you wish I will need one more thing, a greater source of power. I believe in time I could find another way, but I know time is short and you already grow impatient. I am also concerned that rumours of what we attempt are spreading, and that some might be considering my involvement. If I am discovered I cannot hope to defend my actions.\r\n\r\nYour humble and anonymous servant':
        'Çalışmam bitmek üzere, işe yarayacağına inanıyorum; ama bu ilk kabın canlanması ve dilediğinizi yapmakla görevlendirilmesi için bir şeye daha ihtiyacım olacak: daha güçlü bir güç kaynağı. Zamanla başka bir yol bulabileceğime inanıyorum, ama vaktin dar olduğunu ve sabrınızın şimdiden taştığını biliyorum. Ayrıca giriştiğimiz işe dair söylentilerin yayıldığından ve bazılarının benim payımı düşünmeye başlayabileceğinden kaygılıyım. Ortaya çıkarsam eylemlerimi savunmayı umamam.\r\n\r\nAlçakgönüllü ve adsız hizmetkârınız',
    'The Ways of the Thaumaturge - Part 2': 'Tömaturjistin Yolları - Bölüm 2',
    "The 2nd part of a book discussing the workings of the minds of thaumaturges. This volume focuses on the strong connections formed between elevated minds and the traditions surrounding them.\r\n\r\nAn important figure in the life of a thaumaturge is their apprentice, though this relationship isn't always what it might seem. The minds of two thaumaturges can become highly attuned and learn to live and work in harmony. In unison they can be stronger, and when the time comes for the mentor to leave this world behind, their mind will not simply dissipate and be lost entirely, but continue to live in part through their apprentice. Thaumaturges consider their power to be a great gift that must not be lost, but passed on, treasured and nurtured.\r\n\r\nThe tradition of apprenticeship in the Order of Thaumaturges does not only concern the preservation of knowledge and power, but serves also to temper and check the spirits of those who would wield it. It is not only aptitude that is passed on, but the wisdom and temperament of the master. It is not unheard of that apprentices were ultimately deemed to be unfit for such talents and their apprenticeship abandoned.\r\n\r\nIt appears a final chapter was removed from this book, and in its place there is a brief warning against the dangers of bonds formed with beasts, of how these corrupt the mind of a thaumaturge, reducing them to savage beasts themselves.":
        "Tömaturjistlerin zihinlerinin işleyişini ele alan kitabın ikinci bölümü. Bu cilt, yükselmiş zihinler arasında kurulan güçlü bağlara ve bunları çevreleyen geleneklere odaklanıyor.\r\n\r\nBir tömaturjistin hayatındaki önemli kişilerden biri çırağıdır; gerçi bu ilişki her zaman göründüğü gibi değildir. İki tömaturjistin zihni son derece uyumlu hâle gelebilir, birlikte yaşamayı ve çalışmayı öğrenebilir. Birlikte daha güçlü olabilirler ve ustanın bu dünyayı ardında bırakma vakti geldiğinde zihni öylece dağılıp büsbütün yitmez, bir bölümüyle çırağı aracılığıyla yaşamayı sürdürür. Tömaturjistler güçlerini, yitirilmemesi gereken, aktarılması, korunması ve beslenmesi gereken büyük bir armağan sayarlar.\r\n\r\nTömaturjistler Tarikatı'ndaki çıraklık geleneği yalnızca bilginin ve gücün korunmasıyla ilgili değildir; onu kullanacak olanların ruhunu yoğurmaya ve denetlemeye de yarar. Aktarılan yalnızca yetenek değil, ustanın bilgeliği ve mizacıdır. Çırakların sonunda böyle yeteneklere uygun bulunmadığı ve çıraklıklarının bırakıldığı görülmemiş şey değildir.\r\n\r\nAnlaşılan bu kitaptan son bir bölüm çıkarılmış; yerine, hayvanlarla kurulan bağların tehlikelerine dair kısa bir uyarı konmuş: bunların bir tömaturjistin zihnini nasıl yozlaştırdığı, onu kendisi de vahşi bir hayvana dönüştürdüğü.",
    "The time has come, my body is failing. I am certain now that Thaven must be stopped, but I cannot trust his agent to understand, and so I must complete one more dreadful act. I will try to use {®Exanima.Unknown.HimHer} as a vessel even as I die. It is not what I sought, but I believe it will work. I fear it won't be long before my mind and {®Exanima.Unknown.HisHers} are locked in a battle that neither may survive. I must make haste to reach the surface, find sympathetic ears among the Order and warn against the actions of Thaven, and my own.":
        "Vakit geldi, bedenim tükeniyor. Artık Thaven'ın durdurulması gerektiğine eminim, ama adamının bunu anlayacağına güvenemem; bu yüzden bir korkunç işi daha tamamlamalıyım. Ölürken bile {®Exanima.Unknown.HimHer} bir kap olarak kullanmayı deneyeceğim. Aradığım bu değildi, ama işe yarayacağına inanıyorum. Korkarım çok geçmeden benim zihnimle {®Exanima.Unknown.HisHers} zihni, ikisinin de sağ çıkamayacağı bir savaşa kilitlenecek. Yüzeye ulaşmak, Tarikat içinde kulak verecek birilerini bulmak ve hem Thaven'ın hem de kendi yaptıklarıma karşı uyarmak için acele etmeliyim.",
    "The memoirs and research of a necromancer named Corlian of Blackwell. He dedicated his later life to investigating the possibility of an existence beyond one tied to a physical and mortal form. This is known to some as transcendence, and believed to be the ultimate but elusive goal of the Order of Thaumaturges.\r\n\r\nCorlian's research grew in fervour as he became afflicted by an illness from which he would not recover, leading him to acts and experiments that were ruthless in nature. Despite his grim efforts, and many discoveries made, his goal seemed yet distant even as death drew near.\r\n\r\nThe most significant milestone in Corlian's work was the raising of dead that would remain animated even without aid from the necromancer. Corlian saw little use in this, but took it as proof of his theories and an important step towards greater things. He describes this discovery in detail here, someone with an aptitude for such things may be able to replicate it.":
        "Blackwell'li Corlian adlı bir nekromantın anıları ve araştırması. Yaşamının son dönemini, fiziksel ve ölümlü bir biçime bağlı olmayan bir varoluşun olanaklılığını araştırmaya adamış. Bu, kimilerince aşkınlık diye bilinir ve Tömaturjistler Tarikatı'nın nihai ama ele geçmez amacı sayılır.\r\n\r\nCorlian'ın araştırması, iyileşemeyeceği bir hastalığa yakalandıkça daha da hararetlendi ve onu doğası gereği acımasız işlere ve deneylere sürükledi. Karanlık çabalarına ve pek çok keşfine karşın, ölüm yaklaşırken bile amacı hâlâ uzak görünüyordu.\r\n\r\nCorlian'ın çalışmasındaki en önemli dönüm noktası, nekromantın yardımı olmadan da hareketli kalan ölülerin diriltilmesiydi. Corlian bunu pek işe yarar bulmadı, ama kuramlarının kanıtı ve daha büyük şeylere doğru önemli bir adım saydı. Bu keşfi burada ayrıntısıyla anlatıyor; böyle şeylere yatkın biri bunu yineleyebilir.",
    "Dearest Lisiria,\r\n\r\nI hope this letter finds you well, if it finds you at all. The messengers have stopped, but I've been told that for the right price I might get a letter to you. How are things in Scorpe? Here they are burning all writings indiscriminately, they make no exceptions, and take other things too. I set aside some books, telling them they could do no harm, but they would not listen and threatened violence. They took your letters too. When I think of all the books they burn I am filled with rage, but when I thought of them burning your letters I shed tears.\r\n\r\nWhen this is finally all over I will look for you. It will be difficult and it may take time, but I will find you, do not lose hope my love.\r\n\r\nYours lovingly,\r\n\r\nNoran":
        "Sevgili Lisiria,\r\n\r\nUmarım bu mektup seni iyi bulur, tabii eline geçerse. Ulaklar kesildi, ama doğru bedelle sana bir mektup ulaştırabileceğim söylendi. Scorpe'ta işler nasıl? Burada bütün yazılıları ayrım gözetmeden yakıyorlar, hiçbir istisna tanımıyorlar, başka şeyler de alıyorlar. Birkaç kitabı ayırdım, zararı olmaz dedim; ama dinlemediler ve şiddet tehdidinde bulundular. Senin mektuplarını da aldılar. Yaktıkları onca kitabı düşününce içim öfkeyle doluyor, ama senin mektuplarını yaktıklarını düşününce gözyaşı döktüm.\r\n\r\nBütün bunlar nihayet bittiğinde seni arayacağım. Zor olacak ve zaman alabilir, ama seni bulacağım; umudunu yitirme sevdiğim.\r\n\r\nSeni seven,\r\n\r\nNoran",
    'Bread \r\nSalted fish \r\nEggs \r\nCheese and butter\r\nAle \r\nCandles\r\nSoap\r\nCoal\r\n':
        'Ekmek \r\nTuzlu balık \r\nYumurta \r\nPeynir ve tereyağı\r\nBira \r\nMum\r\nSabun\r\nKömür\r\n',
    'Lavender\r\nThyme\r\nChamomile\r\nMarjoram\r\nComfrey\r\nDandelion\r\nNutmeg\r\nGinger\r\nJuniper \r\nAnise \r\nSulphur\r\nSalt\r\nAlum\r\nWax':
        'Lavanta\r\nKekik\r\nPapatya\r\nMercanköşk\r\nKarakafes\r\nKarahindiba\r\nHindistan cevizi\r\nZencefil\r\nArdıç \r\nAnason \r\nKükürt\r\nTuz\r\nŞap\r\nBalmumu',
    'Sketch Book': 'Eskiz Defteri',
    "There are others here, I sensed them. They are not of Hamon's group or my subjects and they did not come the same way as I did. I tracked them for some time and then they quickly vanished from my perception. This is just as it was for the one who escaped, and I know now that he moved through that portal. This must mean there is another somewhere, perhaps it is a more direct way to return to the surface.":
        "Burada başkaları var, onları sezdim. Ne Hamon'un grubundan ne de deneklerimden; üstelik benimle aynı yoldan gelmediler. Bir süre izlerini sürdüm, sonra algımdan hızla silindiler. Tıpkı kaçan kişide olduğu gibi ve artık onun o geçitten geçtiğini biliyorum. Bu, bir yerlerde bir tane daha olduğu anlamına gelmeli; belki yüzeye dönmenin daha dolaysız bir yoludur.",
    'This helmet when worn grants vision even in complete darkness. [sq]':
        'Bu miğfer takıldığında zifiri karanlıkta bile görüş sağlar. [sq]',

    # ---------------- exanima67 (havuz payi sifir: Turkce <= Ingilizce) ----------------
    "Brothers and sisters, it is time to act. They have brought death and ruin upon us all, and now they scramble to hide the proof of their misdeeds and flee. We cannot simply forgive and forget. Those who don't know their past are doomed to repeat mistakes. When the enemy comes knocking at our door we will be unarmed and unprepared. Would you stand idle when assailed? Join us now, we are strong, we are many, and our cause is just.":
        'Kardeşler, harekete geçme vakti. Hepimize ölüm ve yıkım getirdiler, şimdi de suçlarının kanıtını gizleyip kaçmaya çalışıyorlar. Öylece bağışlayıp unutamayız. Geçmişini bilmeyen, hatayı yinelemeye mahkûmdur. Düşman kapımızı çaldığında silahsız ve hazırlıksız olacağız. Saldırıya uğrarken boş mu durursunuz? Bize katılın; güçlüyüz, çoğuz, davamız haklı.',
    'It has come to my attention that you let Fengus borrow your key to the vault, and of course he "misplaced" it. The foreman is respected and we do sometimes let him borrow things, but we don\'t give him access to the vault! Everyone knows he\'s chums with that tavern keep who\'s up to no good. You need to remedy this immediately. If he can\'t produce the key within two days I expect you to take some men and thoroughly search his regular haunts and anyone who works under him. Find that key Donilan, or this will be your last blunder under my command.':
        "Kasa anahtarını Fengus'a ödünç verdiğin kulağıma geldi, o da tabii \"kaybetti\". Ustabaşı saygın biri ve ara sıra ona bir şeyler ödünç veririz, ama kasaya erişim vermeyiz! Hayra alamet olmayan şu meyhanecinin ahbabı olduğunu herkes bilir. Bunu hemen düzeltmelisin. İki gün içinde anahtarı çıkaramazsa, adam alıp uğrak yerlerini ve emrindeki herkesi didik didik aramanı beklerim. Bul şu anahtarı Donilan, yoksa emrimdeki son hatan bu olur.",
    "Keeper Oren,\r\n\r\nAs you know we expect supervisor Seren with a delegation from Manta three days from now. My dislike for those pompous fools has not changed. They revel in their appointment after their supposed success, everyone ignoring the difficulties of our grander scale and all the problems that can be ascribed to nothing but misfortune.\r\n\r\nI want this place to look busy, impress them with our scale and the scope of our endeavour. Hire actors if you must, I don't care who they are so long as they look the part. Make it look grandiose, but orderly, not as if we're scrambling to prevent chaos. I need not tell you what's at stake and what this might mean for all of us, I do not question your ability, but I expect your best effort.":
        "Kâhya Oren,\r\n\r\nBildiğin gibi üç gün sonra denetmen Seren'i Manta'dan bir heyetle bekliyoruz. O kendini beğenmiş budalalara duyduğum hoşnutsuzluk değişmedi. Sözde başarılarının ardından aldıkları görevle böbürleniyorlar; herkes çok daha büyük ölçeğimizin zorluklarını ve şanssızlıktan başka bir şeye yorulamayacak sorunları görmezden geliyor.\r\n\r\nBuranın hareketli görünmesini istiyorum; ölçeğimizle ve işimizin kapsamıyla onları etkile. Gerekirse oyuncu tut; rolüne uydukları sürece kim oldukları umurumda değil. Görkemli görünsün, ama düzenli; kargaşayı önlemek için çırpınıyormuşuz gibi değil. Neyin tehlikede olduğunu ve bunun hepimiz için ne demek olabileceğini sana anlatmama gerek yok; yeteneğinden kuşkum yok, ama en iyi çabanı beklerim.",
    "My love,\r\n\r\nI leave this message as I will not be meeting you here again. I know that when we were last together you noticed the scaling on my neck. Neither of us should pretend it isn't so. I will go under Elento's care. He has told me that the changes are often harmless and that there is no risk of contagion, but in some case they develop gravely, and some also lose their minds. I will not risk you seeing me with disgust, or that I might cause you harm.\r\n\r\nWith all that's taking place I doubt we will see each other again. I've acted as if this were no more than tryst, for fear of upsetting what we had, but know that truly I love you.":
        "Sevgilim,\r\n\r\nBu notu bırakıyorum, çünkü seninle burada bir daha buluşmayacağım. Son birlikteliğimizde boynumdaki pullanmayı fark ettiğini biliyorum. İkimiz de öyle değilmiş gibi yapmayalım. Elento'nun bakımına gireceğim. Değişimlerin çoğu zaman zararsız olduğunu, bulaşma tehlikesi bulunmadığını söyledi; ama kimi durumda ağırlaşıyor, bazıları da aklını yitiriyor. Bana tiksintiyle bakmanı ya da sana zarar verme olasılığını göze almayacağım.\r\n\r\nOlan biten her şeyin ortasında bir daha görüşeceğimizi sanmıyorum. Elimizdekini bozmaktan korktuğum için bunu geçici bir kaçamak gibi gösterdim, ama bil ki seni gerçekten seviyorum.",
    "I'm quite certain that young Thelia has a strong talent. She does not know it, but she perceives and discerns the thoughts of others in ways that ordinary people cannot. I'm sure you're aware of her particular empathy, and perhaps you too have suspected there's more to it.\r\n\r\nI do not presume to suggest how you should handle it, and I'm sure you'd want to keep it quiet as things are, but she is already eagerly active and well liked in our community and her talents could be of great use to us. Perhaps you could talk to her, and she could put her ability to discreet use. I hope you know I would never put her in harm's way. I think her danger may be greater if she continues to be unaware of what she does.":
        "Genç Thelia'nın güçlü bir yeteneği olduğuna epey eminim. Kendisi bilmiyor, ama başkalarının düşüncelerini sıradan insanların yapamayacağı biçimde algılayıp ayırt ediyor. Onun özel duyarlılığının farkında olduğunuza eminim; belki siz de işin daha fazlası olduğundan kuşkulandınız.\r\n\r\nBunu nasıl ele almanız gerektiğini söylemeye kalkışmam ve işler bu hâldeyken sessiz tutmak isteyeceğinizden eminim; ama o şimdiden topluluğumuzda istekli, etkin ve sevilen biri, yetenekleri de bize çok yarayabilir. Belki onunla konuşabilirsiniz, o da yetisini ihtiyatla kullanabilir. Onu asla tehlikeye atmayacağımı bildiğinizi umarım. Bence ne yaptığından habersiz kalmayı sürdürürse tehlike daha da büyür.",
    'Alright, so I admit the new lad may indeed be a spy as you\'ve said. He asks too many pertinent questions, and his cheery, helpful demeanour does not fit the times. Still I don\'t think that your boys should "ask him some questions" as they eloquently put it. We should keep a close eye on him and discover to whom he might report, maybe give him something false and see what comes of it. We\'re more likely to make our advantage this way, and there\'s still a chance that all we sense is our own irritation at his manner.\r\n\r\nThere may be another way for us to know the truth of it, but I cannot speak of it yet.':
        'Peki, kabul: yeni delikanlı dediğin gibi gerçekten casus olabilir. Fazla yerinde sorular soruyor ve şu neşeli, yardımsever tavrı bu zamana hiç uymuyor. Yine de adamlarının, kendi zarif deyişleriyle, "ona birkaç soru sorması" gerektiğini düşünmüyorum. Onu yakından gözlemeli ve kime rapor verdiğini bulmalıyız; belki ona yanlış bir bilgi verip ne olacağını görürüz. Bu yolla üstünlük sağlamamız daha olası; üstelik sezdiğimiz şeyin sırf tavrına duyduğumuz rahatsızlık olma ihtimali de var.\r\n\r\nİşin doğrusunu öğrenmenin başka bir yolu olabilir, ama ondan henüz söz edemem.',
    'The inscription uses words and phrasing unfamiliar to you, but you are able to discern some of its meaning.\r\n\r\nIt appears to profess that the body is the seed of the mind and when laid to rest in peace the mind may bloom and take its true form.':
        'Yazıtta sana yabancı sözcükler ve deyişler kullanılmış, ama anlamının bir kısmını çıkarabiliyorsun.\r\n\r\nAnlaşılan bedenin zihnin tohumu olduğunu, huzur içinde toprağa verildiğinde zihnin açıp gerçek biçimini alabileceğini savunuyor.',

    # ---------------- exanima07_sw ----------------
    "This journal is filled with diagrams of what look like strange organs, and some others you don't understand. It seems various fluids were being tested on fleshy tissues, most of the names are very unusual. On the last written page, there seem to be the author's dying words:\r\n\r\n[scrp=i]I think I will die here. I can hear them at the door, scratching. I cannot escape.\r\n\r\nNephil, know that your concoction was entirely ineffective in deterring the monsters. I think we've got it all wrong, something else is driving them. I do not blame you, it was an honor to work with you, and I knew the risk I was taking. \r\n\r\nPlease take care of Esthra.":
        "Bu günlük, tuhaf organları andıran çizimlerle ve anlam veremediğin başkalarıyla dolu. Anlaşılan etli dokular üzerinde çeşitli sıvılar deneniyormuş; adların çoğu pek alışılmadık. Yazılmış son sayfada, yazarın ölüm döşeğindeki sözleri var gibi:\r\n\r\n[scrp=i]Sanırım burada öleceğim. Onları kapıda duyabiliyorum, tırmalıyorlar. Kaçamam.\r\n\r\nNephil, bil ki karışımın canavarları uzak tutmakta hiçbir işe yaramadı. Sanırım her şeyi yanlış anladık, onları başka bir şey sürüklüyor. Seni suçlamıyorum; seninle çalışmak bir onurdu ve göze aldığım riski biliyordum. \r\n\r\nLütfen Esthra'ya göz kulak ol.",
}

# Gomulu RDB indeksinin DISINDA, havuzun ardinda duran metinler. Sinirlarini
# gosteren bir indeks bulunamadi; bu yuzden AYNI BAYT UZUNLUGUNDA yerinde
# degistirilirler (kisa kalan yer bosluklarla doldurulur). Boylece dosyanin
# hicbir bayti kaymaz.  {dosya_adi: {ingilizce: turkce}}
YERINDE = {
    'exanima02.rfc': {
        'Mathematics Made Simple: A Classroom Companion':
            'Matematik Kolaylaştı: Sınıf Arkadaşınız',
        '"Mathematics Made Simple" is an essential textbook for students looking to grasp the foundations of basic math. Written with clarity and precision, this book covers essential topics like arithmetic, geometry, and algebra in a straightforward and approachable way. Packed with practical examples and exercises, it\'s the ideal resource to help learners build a solid mathematical foundation, making it a staple in classrooms to foster mathematical understanding.':
            '"Matematik Kolaylaştı", temel matematiğin esaslarını kavramak isteyen öğrenciler için vazgeçilmez bir ders kitabı. Açık ve titiz bir dille yazılmış; aritmetik, geometri ve cebir gibi temel konuları yalın ve anlaşılır biçimde ele alıyor. Uygulamalı örnek ve alıştırmalarla dolu olması, onu sağlam bir matematik temeli kurmak isteyenler için ideal bir kaynak ve matematiksel kavrayışı geliştirmek adına sınıfların vazgeçilmezi kılıyor.',
    },
}
